package cn.yuntangnet.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BusinessContentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_content
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_content
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_content
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    public BusinessContentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table business_content
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andContentThemeIsNull() {
            addCriterion("content_theme is null");
            return (Criteria) this;
        }

        public Criteria andContentThemeIsNotNull() {
            addCriterion("content_theme is not null");
            return (Criteria) this;
        }

        public Criteria andContentThemeEqualTo(String value) {
            addCriterion("content_theme =", value, "contentTheme");
            return (Criteria) this;
        }

        public Criteria andContentThemeNotEqualTo(String value) {
            addCriterion("content_theme <>", value, "contentTheme");
            return (Criteria) this;
        }

        public Criteria andContentThemeGreaterThan(String value) {
            addCriterion("content_theme >", value, "contentTheme");
            return (Criteria) this;
        }

        public Criteria andContentThemeGreaterThanOrEqualTo(String value) {
            addCriterion("content_theme >=", value, "contentTheme");
            return (Criteria) this;
        }

        public Criteria andContentThemeLessThan(String value) {
            addCriterion("content_theme <", value, "contentTheme");
            return (Criteria) this;
        }

        public Criteria andContentThemeLessThanOrEqualTo(String value) {
            addCriterion("content_theme <=", value, "contentTheme");
            return (Criteria) this;
        }

        public Criteria andContentThemeLike(String value) {
            addCriterion("content_theme like", value, "contentTheme");
            return (Criteria) this;
        }

        public Criteria andContentThemeNotLike(String value) {
            addCriterion("content_theme not like", value, "contentTheme");
            return (Criteria) this;
        }

        public Criteria andContentThemeIn(List<String> values) {
            addCriterion("content_theme in", values, "contentTheme");
            return (Criteria) this;
        }

        public Criteria andContentThemeNotIn(List<String> values) {
            addCriterion("content_theme not in", values, "contentTheme");
            return (Criteria) this;
        }

        public Criteria andContentThemeBetween(String value1, String value2) {
            addCriterion("content_theme between", value1, value2, "contentTheme");
            return (Criteria) this;
        }

        public Criteria andContentThemeNotBetween(String value1, String value2) {
            addCriterion("content_theme not between", value1, value2, "contentTheme");
            return (Criteria) this;
        }

        public Criteria andContentTeacherIsNull() {
            addCriterion("content_teacher is null");
            return (Criteria) this;
        }

        public Criteria andContentTeacherIsNotNull() {
            addCriterion("content_teacher is not null");
            return (Criteria) this;
        }

        public Criteria andContentTeacherEqualTo(String value) {
            addCriterion("content_teacher =", value, "contentTeacher");
            return (Criteria) this;
        }

        public Criteria andContentTeacherNotEqualTo(String value) {
            addCriterion("content_teacher <>", value, "contentTeacher");
            return (Criteria) this;
        }

        public Criteria andContentTeacherGreaterThan(String value) {
            addCriterion("content_teacher >", value, "contentTeacher");
            return (Criteria) this;
        }

        public Criteria andContentTeacherGreaterThanOrEqualTo(String value) {
            addCriterion("content_teacher >=", value, "contentTeacher");
            return (Criteria) this;
        }

        public Criteria andContentTeacherLessThan(String value) {
            addCriterion("content_teacher <", value, "contentTeacher");
            return (Criteria) this;
        }

        public Criteria andContentTeacherLessThanOrEqualTo(String value) {
            addCriterion("content_teacher <=", value, "contentTeacher");
            return (Criteria) this;
        }

        public Criteria andContentTeacherLike(String value) {
            addCriterion("content_teacher like", value, "contentTeacher");
            return (Criteria) this;
        }

        public Criteria andContentTeacherNotLike(String value) {
            addCriterion("content_teacher not like", value, "contentTeacher");
            return (Criteria) this;
        }

        public Criteria andContentTeacherIn(List<String> values) {
            addCriterion("content_teacher in", values, "contentTeacher");
            return (Criteria) this;
        }

        public Criteria andContentTeacherNotIn(List<String> values) {
            addCriterion("content_teacher not in", values, "contentTeacher");
            return (Criteria) this;
        }

        public Criteria andContentTeacherBetween(String value1, String value2) {
            addCriterion("content_teacher between", value1, value2, "contentTeacher");
            return (Criteria) this;
        }

        public Criteria andContentTeacherNotBetween(String value1, String value2) {
            addCriterion("content_teacher not between", value1, value2, "contentTeacher");
            return (Criteria) this;
        }

        public Criteria andContentMoneyIsNull() {
            addCriterion("content_money is null");
            return (Criteria) this;
        }

        public Criteria andContentMoneyIsNotNull() {
            addCriterion("content_money is not null");
            return (Criteria) this;
        }

        public Criteria andContentMoneyEqualTo(Long value) {
            addCriterion("content_money =", value, "contentMoney");
            return (Criteria) this;
        }

        public Criteria andContentMoneyNotEqualTo(Long value) {
            addCriterion("content_money <>", value, "contentMoney");
            return (Criteria) this;
        }

        public Criteria andContentMoneyGreaterThan(Long value) {
            addCriterion("content_money >", value, "contentMoney");
            return (Criteria) this;
        }

        public Criteria andContentMoneyGreaterThanOrEqualTo(Long value) {
            addCriterion("content_money >=", value, "contentMoney");
            return (Criteria) this;
        }

        public Criteria andContentMoneyLessThan(Long value) {
            addCriterion("content_money <", value, "contentMoney");
            return (Criteria) this;
        }

        public Criteria andContentMoneyLessThanOrEqualTo(Long value) {
            addCriterion("content_money <=", value, "contentMoney");
            return (Criteria) this;
        }

        public Criteria andContentMoneyIn(List<Long> values) {
            addCriterion("content_money in", values, "contentMoney");
            return (Criteria) this;
        }

        public Criteria andContentMoneyNotIn(List<Long> values) {
            addCriterion("content_money not in", values, "contentMoney");
            return (Criteria) this;
        }

        public Criteria andContentMoneyBetween(Long value1, Long value2) {
            addCriterion("content_money between", value1, value2, "contentMoney");
            return (Criteria) this;
        }

        public Criteria andContentMoneyNotBetween(Long value1, Long value2) {
            addCriterion("content_money not between", value1, value2, "contentMoney");
            return (Criteria) this;
        }

        public Criteria andContentDetailsIsNull() {
            addCriterion("content_details is null");
            return (Criteria) this;
        }

        public Criteria andContentDetailsIsNotNull() {
            addCriterion("content_details is not null");
            return (Criteria) this;
        }

        public Criteria andContentDetailsEqualTo(String value) {
            addCriterion("content_details =", value, "contentDetails");
            return (Criteria) this;
        }

        public Criteria andContentDetailsNotEqualTo(String value) {
            addCriterion("content_details <>", value, "contentDetails");
            return (Criteria) this;
        }

        public Criteria andContentDetailsGreaterThan(String value) {
            addCriterion("content_details >", value, "contentDetails");
            return (Criteria) this;
        }

        public Criteria andContentDetailsGreaterThanOrEqualTo(String value) {
            addCriterion("content_details >=", value, "contentDetails");
            return (Criteria) this;
        }

        public Criteria andContentDetailsLessThan(String value) {
            addCriterion("content_details <", value, "contentDetails");
            return (Criteria) this;
        }

        public Criteria andContentDetailsLessThanOrEqualTo(String value) {
            addCriterion("content_details <=", value, "contentDetails");
            return (Criteria) this;
        }

        public Criteria andContentDetailsLike(String value) {
            addCriterion("content_details like", value, "contentDetails");
            return (Criteria) this;
        }

        public Criteria andContentDetailsNotLike(String value) {
            addCriterion("content_details not like", value, "contentDetails");
            return (Criteria) this;
        }

        public Criteria andContentDetailsIn(List<String> values) {
            addCriterion("content_details in", values, "contentDetails");
            return (Criteria) this;
        }

        public Criteria andContentDetailsNotIn(List<String> values) {
            addCriterion("content_details not in", values, "contentDetails");
            return (Criteria) this;
        }

        public Criteria andContentDetailsBetween(String value1, String value2) {
            addCriterion("content_details between", value1, value2, "contentDetails");
            return (Criteria) this;
        }

        public Criteria andContentDetailsNotBetween(String value1, String value2) {
            addCriterion("content_details not between", value1, value2, "contentDetails");
            return (Criteria) this;
        }

        public Criteria andContentPayingCountIsNull() {
            addCriterion("content_paying_count is null");
            return (Criteria) this;
        }

        public Criteria andContentPayingCountIsNotNull() {
            addCriterion("content_paying_count is not null");
            return (Criteria) this;
        }

        public Criteria andContentPayingCountEqualTo(Integer value) {
            addCriterion("content_paying_count =", value, "contentPayingCount");
            return (Criteria) this;
        }

        public Criteria andContentPayingCountNotEqualTo(Integer value) {
            addCriterion("content_paying_count <>", value, "contentPayingCount");
            return (Criteria) this;
        }

        public Criteria andContentPayingCountGreaterThan(Integer value) {
            addCriterion("content_paying_count >", value, "contentPayingCount");
            return (Criteria) this;
        }

        public Criteria andContentPayingCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("content_paying_count >=", value, "contentPayingCount");
            return (Criteria) this;
        }

        public Criteria andContentPayingCountLessThan(Integer value) {
            addCriterion("content_paying_count <", value, "contentPayingCount");
            return (Criteria) this;
        }

        public Criteria andContentPayingCountLessThanOrEqualTo(Integer value) {
            addCriterion("content_paying_count <=", value, "contentPayingCount");
            return (Criteria) this;
        }

        public Criteria andContentPayingCountIn(List<Integer> values) {
            addCriterion("content_paying_count in", values, "contentPayingCount");
            return (Criteria) this;
        }

        public Criteria andContentPayingCountNotIn(List<Integer> values) {
            addCriterion("content_paying_count not in", values, "contentPayingCount");
            return (Criteria) this;
        }

        public Criteria andContentPayingCountBetween(Integer value1, Integer value2) {
            addCriterion("content_paying_count between", value1, value2, "contentPayingCount");
            return (Criteria) this;
        }

        public Criteria andContentPayingCountNotBetween(Integer value1, Integer value2) {
            addCriterion("content_paying_count not between", value1, value2, "contentPayingCount");
            return (Criteria) this;
        }

        public Criteria andContentSigninCountIsNull() {
            addCriterion("content_signin_count is null");
            return (Criteria) this;
        }

        public Criteria andContentSigninCountIsNotNull() {
            addCriterion("content_signin_count is not null");
            return (Criteria) this;
        }

        public Criteria andContentSigninCountEqualTo(Integer value) {
            addCriterion("content_signin_count =", value, "contentSigninCount");
            return (Criteria) this;
        }

        public Criteria andContentSigninCountNotEqualTo(Integer value) {
            addCriterion("content_signin_count <>", value, "contentSigninCount");
            return (Criteria) this;
        }

        public Criteria andContentSigninCountGreaterThan(Integer value) {
            addCriterion("content_signin_count >", value, "contentSigninCount");
            return (Criteria) this;
        }

        public Criteria andContentSigninCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("content_signin_count >=", value, "contentSigninCount");
            return (Criteria) this;
        }

        public Criteria andContentSigninCountLessThan(Integer value) {
            addCriterion("content_signin_count <", value, "contentSigninCount");
            return (Criteria) this;
        }

        public Criteria andContentSigninCountLessThanOrEqualTo(Integer value) {
            addCriterion("content_signin_count <=", value, "contentSigninCount");
            return (Criteria) this;
        }

        public Criteria andContentSigninCountIn(List<Integer> values) {
            addCriterion("content_signin_count in", values, "contentSigninCount");
            return (Criteria) this;
        }

        public Criteria andContentSigninCountNotIn(List<Integer> values) {
            addCriterion("content_signin_count not in", values, "contentSigninCount");
            return (Criteria) this;
        }

        public Criteria andContentSigninCountBetween(Integer value1, Integer value2) {
            addCriterion("content_signin_count between", value1, value2, "contentSigninCount");
            return (Criteria) this;
        }

        public Criteria andContentSigninCountNotBetween(Integer value1, Integer value2) {
            addCriterion("content_signin_count not between", value1, value2, "contentSigninCount");
            return (Criteria) this;
        }

        public Criteria andContentTotalMoneyIsNull() {
            addCriterion("content_total_money is null");
            return (Criteria) this;
        }

        public Criteria andContentTotalMoneyIsNotNull() {
            addCriterion("content_total_money is not null");
            return (Criteria) this;
        }

        public Criteria andContentTotalMoneyEqualTo(Long value) {
            addCriterion("content_total_money =", value, "contentTotalMoney");
            return (Criteria) this;
        }

        public Criteria andContentTotalMoneyNotEqualTo(Long value) {
            addCriterion("content_total_money <>", value, "contentTotalMoney");
            return (Criteria) this;
        }

        public Criteria andContentTotalMoneyGreaterThan(Long value) {
            addCriterion("content_total_money >", value, "contentTotalMoney");
            return (Criteria) this;
        }

        public Criteria andContentTotalMoneyGreaterThanOrEqualTo(Long value) {
            addCriterion("content_total_money >=", value, "contentTotalMoney");
            return (Criteria) this;
        }

        public Criteria andContentTotalMoneyLessThan(Long value) {
            addCriterion("content_total_money <", value, "contentTotalMoney");
            return (Criteria) this;
        }

        public Criteria andContentTotalMoneyLessThanOrEqualTo(Long value) {
            addCriterion("content_total_money <=", value, "contentTotalMoney");
            return (Criteria) this;
        }

        public Criteria andContentTotalMoneyIn(List<Long> values) {
            addCriterion("content_total_money in", values, "contentTotalMoney");
            return (Criteria) this;
        }

        public Criteria andContentTotalMoneyNotIn(List<Long> values) {
            addCriterion("content_total_money not in", values, "contentTotalMoney");
            return (Criteria) this;
        }

        public Criteria andContentTotalMoneyBetween(Long value1, Long value2) {
            addCriterion("content_total_money between", value1, value2, "contentTotalMoney");
            return (Criteria) this;
        }

        public Criteria andContentTotalMoneyNotBetween(Long value1, Long value2) {
            addCriterion("content_total_money not between", value1, value2, "contentTotalMoney");
            return (Criteria) this;
        }

        public Criteria andContentStatusIsNull() {
            addCriterion("content_status is null");
            return (Criteria) this;
        }

        public Criteria andContentStatusIsNotNull() {
            addCriterion("content_status is not null");
            return (Criteria) this;
        }

        public Criteria andContentStatusEqualTo(String value) {
            addCriterion("content_status =", value, "contentStatus");
            return (Criteria) this;
        }

        public Criteria andContentStatusNotEqualTo(String value) {
            addCriterion("content_status <>", value, "contentStatus");
            return (Criteria) this;
        }

        public Criteria andContentStatusGreaterThan(String value) {
            addCriterion("content_status >", value, "contentStatus");
            return (Criteria) this;
        }

        public Criteria andContentStatusGreaterThanOrEqualTo(String value) {
            addCriterion("content_status >=", value, "contentStatus");
            return (Criteria) this;
        }

        public Criteria andContentStatusLessThan(String value) {
            addCriterion("content_status <", value, "contentStatus");
            return (Criteria) this;
        }

        public Criteria andContentStatusLessThanOrEqualTo(String value) {
            addCriterion("content_status <=", value, "contentStatus");
            return (Criteria) this;
        }

        public Criteria andContentStatusLike(String value) {
            addCriterion("content_status like", value, "contentStatus");
            return (Criteria) this;
        }

        public Criteria andContentStatusNotLike(String value) {
            addCriterion("content_status not like", value, "contentStatus");
            return (Criteria) this;
        }

        public Criteria andContentStatusIn(List<String> values) {
            addCriterion("content_status in", values, "contentStatus");
            return (Criteria) this;
        }

        public Criteria andContentStatusNotIn(List<String> values) {
            addCriterion("content_status not in", values, "contentStatus");
            return (Criteria) this;
        }

        public Criteria andContentStatusBetween(String value1, String value2) {
            addCriterion("content_status between", value1, value2, "contentStatus");
            return (Criteria) this;
        }

        public Criteria andContentStatusNotBetween(String value1, String value2) {
            addCriterion("content_status not between", value1, value2, "contentStatus");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNull() {
            addCriterion("begin_time is null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNotNull() {
            addCriterion("begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeEqualTo(Date value) {
            addCriterion("begin_time =", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotEqualTo(Date value) {
            addCriterion("begin_time <>", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThan(Date value) {
            addCriterion("begin_time >", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("begin_time >=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThan(Date value) {
            addCriterion("begin_time <", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("begin_time <=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIn(List<Date> values) {
            addCriterion("begin_time in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotIn(List<Date> values) {
            addCriterion("begin_time not in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeBetween(Date value1, Date value2) {
            addCriterion("begin_time between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("begin_time not between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andAdminNameIsNull() {
            addCriterion("admin_name is null");
            return (Criteria) this;
        }

        public Criteria andAdminNameIsNotNull() {
            addCriterion("admin_name is not null");
            return (Criteria) this;
        }

        public Criteria andAdminNameEqualTo(String value) {
            addCriterion("admin_name =", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotEqualTo(String value) {
            addCriterion("admin_name <>", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameGreaterThan(String value) {
            addCriterion("admin_name >", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameGreaterThanOrEqualTo(String value) {
            addCriterion("admin_name >=", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLessThan(String value) {
            addCriterion("admin_name <", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLessThanOrEqualTo(String value) {
            addCriterion("admin_name <=", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLike(String value) {
            addCriterion("admin_name like", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotLike(String value) {
            addCriterion("admin_name not like", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameIn(List<String> values) {
            addCriterion("admin_name in", values, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotIn(List<String> values) {
            addCriterion("admin_name not in", values, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameBetween(String value1, String value2) {
            addCriterion("admin_name between", value1, value2, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotBetween(String value1, String value2) {
            addCriterion("admin_name not between", value1, value2, "adminName");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Boolean value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Boolean value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Boolean value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Boolean value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Boolean> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Boolean> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table business_content
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table business_content
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}