package cn.yuntangnet.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table business_content
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BusinessContent implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   主题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.content_theme
     *
     * @mbg.generated
     */
    private String contentTheme;

    /**
     * Database Column Remarks:
     *   讲师
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.content_teacher
     *
     * @mbg.generated
     */
    private String contentTeacher;

    /**
     * Database Column Remarks:
     *   活动费用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.content_money
     *
     * @mbg.generated
     */
    private Long contentMoney;

    /**
     * Database Column Remarks:
     *   活动说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.content_details
     *
     * @mbg.generated
     */
    private String contentDetails;

    /**
     * Database Column Remarks:
     *   付款用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.content_paying_count
     *
     * @mbg.generated
     */
    private Integer contentPayingCount;

    /**
     * Database Column Remarks:
     *   到场人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.content_signin_count
     *
     * @mbg.generated
     */
    private Integer contentSigninCount;

    /**
     * Database Column Remarks:
     *   统计已缴费用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.content_total_money
     *
     * @mbg.generated
     */
    private Long contentTotalMoney;

    /**
     * Database Column Remarks:
     *   活动状态:1.已开启,0.未开启 2.已结束,3已关闭
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.content_status
     *
     * @mbg.generated
     */
    private String contentStatus;

    /**
     * Database Column Remarks:
     *   开始日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.begin_time
     *
     * @mbg.generated
     */
    private Date beginTime;

    /**
     * Database Column Remarks:
     *   结束日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     * Database Column Remarks:
     *   操作的管理员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.admin_name
     *
     * @mbg.generated
     */
    private String adminName;

    /**
     * Database Column Remarks:
     *   是否已删除：1.已删除，0.未删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.is_deleted
     *
     * @mbg.generated
     */
    private Boolean isDeleted;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_content.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_content
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.id
     *
     * @return the value of business_content.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.id
     *
     * @param id the value for business_content.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.content_theme
     *
     * @return the value of business_content.content_theme
     *
     * @mbg.generated
     */
    public String getContentTheme() {
        return contentTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.content_theme
     *
     * @param contentTheme the value for business_content.content_theme
     *
     * @mbg.generated
     */
    public void setContentTheme(String contentTheme) {
        this.contentTheme = contentTheme == null ? null : contentTheme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.content_teacher
     *
     * @return the value of business_content.content_teacher
     *
     * @mbg.generated
     */
    public String getContentTeacher() {
        return contentTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.content_teacher
     *
     * @param contentTeacher the value for business_content.content_teacher
     *
     * @mbg.generated
     */
    public void setContentTeacher(String contentTeacher) {
        this.contentTeacher = contentTeacher == null ? null : contentTeacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.content_money
     *
     * @return the value of business_content.content_money
     *
     * @mbg.generated
     */
    public Long getContentMoney() {
        return contentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.content_money
     *
     * @param contentMoney the value for business_content.content_money
     *
     * @mbg.generated
     */
    public void setContentMoney(Long contentMoney) {
        this.contentMoney = contentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.content_details
     *
     * @return the value of business_content.content_details
     *
     * @mbg.generated
     */
    public String getContentDetails() {
        return contentDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.content_details
     *
     * @param contentDetails the value for business_content.content_details
     *
     * @mbg.generated
     */
    public void setContentDetails(String contentDetails) {
        this.contentDetails = contentDetails == null ? null : contentDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.content_paying_count
     *
     * @return the value of business_content.content_paying_count
     *
     * @mbg.generated
     */
    public Integer getContentPayingCount() {
        return contentPayingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.content_paying_count
     *
     * @param contentPayingCount the value for business_content.content_paying_count
     *
     * @mbg.generated
     */
    public void setContentPayingCount(Integer contentPayingCount) {
        this.contentPayingCount = contentPayingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.content_signin_count
     *
     * @return the value of business_content.content_signin_count
     *
     * @mbg.generated
     */
    public Integer getContentSigninCount() {
        return contentSigninCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.content_signin_count
     *
     * @param contentSigninCount the value for business_content.content_signin_count
     *
     * @mbg.generated
     */
    public void setContentSigninCount(Integer contentSigninCount) {
        this.contentSigninCount = contentSigninCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.content_total_money
     *
     * @return the value of business_content.content_total_money
     *
     * @mbg.generated
     */
    public Long getContentTotalMoney() {
        return contentTotalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.content_total_money
     *
     * @param contentTotalMoney the value for business_content.content_total_money
     *
     * @mbg.generated
     */
    public void setContentTotalMoney(Long contentTotalMoney) {
        this.contentTotalMoney = contentTotalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.content_status
     *
     * @return the value of business_content.content_status
     *
     * @mbg.generated
     */
    public String getContentStatus() {
        return contentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.content_status
     *
     * @param contentStatus the value for business_content.content_status
     *
     * @mbg.generated
     */
    public void setContentStatus(String contentStatus) {
        this.contentStatus = contentStatus == null ? null : contentStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.begin_time
     *
     * @return the value of business_content.begin_time
     *
     * @mbg.generated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.begin_time
     *
     * @param beginTime the value for business_content.begin_time
     *
     * @mbg.generated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.end_time
     *
     * @return the value of business_content.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.end_time
     *
     * @param endTime the value for business_content.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.admin_name
     *
     * @return the value of business_content.admin_name
     *
     * @mbg.generated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.admin_name
     *
     * @param adminName the value for business_content.admin_name
     *
     * @mbg.generated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.is_deleted
     *
     * @return the value of business_content.is_deleted
     *
     * @mbg.generated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.is_deleted
     *
     * @param isDeleted the value for business_content.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.gmt_create
     *
     * @return the value of business_content.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.gmt_create
     *
     * @param gmtCreate the value for business_content.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_content.gmt_modified
     *
     * @return the value of business_content.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_content.gmt_modified
     *
     * @param gmtModified the value for business_content.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}