package cn.yuntangnet.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table system_contract
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SystemContract implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   订单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   用户姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   手机号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.user_phone
     *
     * @mbg.generated
     */
    private String userPhone;

    /**
     * Database Column Remarks:
     *   所属代理商
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.agent_name
     *
     * @mbg.generated
     */
    private String agentName;

    /**
     * Database Column Remarks:
     *   合同信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.contract_msg
     *
     * @mbg.generated
     */
    private String contractMsg;

    /**
     * Database Column Remarks:
     *   附件1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.annex1
     *
     * @mbg.generated
     */
    private String annex1;

    /**
     * Database Column Remarks:
     *   提交人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.send_id
     *
     * @mbg.generated
     */
    private Long sendId;

    /**
     * Database Column Remarks:
     *   提交人微信昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.send_name
     *
     * @mbg.generated
     */
    private String sendName;

    /**
     * Database Column Remarks:
     *   附件2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.annex2
     *
     * @mbg.generated
     */
    private String annex2;

    /**
     * Database Column Remarks:
     *   合同状态:1.未提交,2.已提交,3.已审核
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.contract_status
     *
     * @mbg.generated
     */
    private String contractStatus;

    /**
     * Database Column Remarks:
     *   审核的管理员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.admin_name
     *
     * @mbg.generated
     */
    private String adminName;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_contract.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_contract
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.id
     *
     * @return the value of system_contract.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.id
     *
     * @param id the value for system_contract.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.order_id
     *
     * @return the value of system_contract.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.order_id
     *
     * @param orderId the value for system_contract.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.user_name
     *
     * @return the value of system_contract.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.user_name
     *
     * @param userName the value for system_contract.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.user_phone
     *
     * @return the value of system_contract.user_phone
     *
     * @mbg.generated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.user_phone
     *
     * @param userPhone the value for system_contract.user_phone
     *
     * @mbg.generated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.agent_name
     *
     * @return the value of system_contract.agent_name
     *
     * @mbg.generated
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.agent_name
     *
     * @param agentName the value for system_contract.agent_name
     *
     * @mbg.generated
     */
    public void setAgentName(String agentName) {
        this.agentName = agentName == null ? null : agentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.contract_msg
     *
     * @return the value of system_contract.contract_msg
     *
     * @mbg.generated
     */
    public String getContractMsg() {
        return contractMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.contract_msg
     *
     * @param contractMsg the value for system_contract.contract_msg
     *
     * @mbg.generated
     */
    public void setContractMsg(String contractMsg) {
        this.contractMsg = contractMsg == null ? null : contractMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.annex1
     *
     * @return the value of system_contract.annex1
     *
     * @mbg.generated
     */
    public String getAnnex1() {
        return annex1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.annex1
     *
     * @param annex1 the value for system_contract.annex1
     *
     * @mbg.generated
     */
    public void setAnnex1(String annex1) {
        this.annex1 = annex1 == null ? null : annex1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.send_id
     *
     * @return the value of system_contract.send_id
     *
     * @mbg.generated
     */
    public Long getSendId() {
        return sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.send_id
     *
     * @param sendId the value for system_contract.send_id
     *
     * @mbg.generated
     */
    public void setSendId(Long sendId) {
        this.sendId = sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.send_name
     *
     * @return the value of system_contract.send_name
     *
     * @mbg.generated
     */
    public String getSendName() {
        return sendName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.send_name
     *
     * @param sendName the value for system_contract.send_name
     *
     * @mbg.generated
     */
    public void setSendName(String sendName) {
        this.sendName = sendName == null ? null : sendName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.annex2
     *
     * @return the value of system_contract.annex2
     *
     * @mbg.generated
     */
    public String getAnnex2() {
        return annex2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.annex2
     *
     * @param annex2 the value for system_contract.annex2
     *
     * @mbg.generated
     */
    public void setAnnex2(String annex2) {
        this.annex2 = annex2 == null ? null : annex2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.contract_status
     *
     * @return the value of system_contract.contract_status
     *
     * @mbg.generated
     */
    public String getContractStatus() {
        return contractStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.contract_status
     *
     * @param contractStatus the value for system_contract.contract_status
     *
     * @mbg.generated
     */
    public void setContractStatus(String contractStatus) {
        this.contractStatus = contractStatus == null ? null : contractStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.admin_name
     *
     * @return the value of system_contract.admin_name
     *
     * @mbg.generated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.admin_name
     *
     * @param adminName the value for system_contract.admin_name
     *
     * @mbg.generated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.gmt_create
     *
     * @return the value of system_contract.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.gmt_create
     *
     * @param gmtCreate the value for system_contract.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_contract.gmt_modified
     *
     * @return the value of system_contract.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_contract.gmt_modified
     *
     * @param gmtModified the value for system_contract.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}