package cn.yuntangnet.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table work_order
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class WorkOrder implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   下单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.user_wechat_id
     *
     * @mbg.generated
     */
    private Long userWechatId;

    /**
     * Database Column Remarks:
     *   工单类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     * Database Column Remarks:
     *   代理商区域
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.agent_area
     *
     * @mbg.generated
     */
    private String agentArea;

    /**
     * Database Column Remarks:
     *   代理商姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.agent_name
     *
     * @mbg.generated
     */
    private String agentName;

    /**
     * Database Column Remarks:
     *   联系手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.user_phone
     *
     * @mbg.generated
     */
    private String userPhone;

    /**
     * Database Column Remarks:
     *   订单状态:1未处理,2.已处理
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.order_status
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     * Database Column Remarks:
     *   问题描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.question
     *
     * @mbg.generated
     */
    private String question;

    /**
     * Database Column Remarks:
     *   处理意见
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.msg
     *
     * @mbg.generated
     */
    private String msg;

    /**
     * Database Column Remarks:
     *   附件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.annex
     *
     * @mbg.generated
     */
    private String annex;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.id
     *
     * @return the value of work_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.id
     *
     * @param id the value for work_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.user_wechat_id
     *
     * @return the value of work_order.user_wechat_id
     *
     * @mbg.generated
     */
    public Long getUserWechatId() {
        return userWechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.user_wechat_id
     *
     * @param userWechatId the value for work_order.user_wechat_id
     *
     * @mbg.generated
     */
    public void setUserWechatId(Long userWechatId) {
        this.userWechatId = userWechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.order_type
     *
     * @return the value of work_order.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.order_type
     *
     * @param orderType the value for work_order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.agent_area
     *
     * @return the value of work_order.agent_area
     *
     * @mbg.generated
     */
    public String getAgentArea() {
        return agentArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.agent_area
     *
     * @param agentArea the value for work_order.agent_area
     *
     * @mbg.generated
     */
    public void setAgentArea(String agentArea) {
        this.agentArea = agentArea == null ? null : agentArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.agent_name
     *
     * @return the value of work_order.agent_name
     *
     * @mbg.generated
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.agent_name
     *
     * @param agentName the value for work_order.agent_name
     *
     * @mbg.generated
     */
    public void setAgentName(String agentName) {
        this.agentName = agentName == null ? null : agentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.user_phone
     *
     * @return the value of work_order.user_phone
     *
     * @mbg.generated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.user_phone
     *
     * @param userPhone the value for work_order.user_phone
     *
     * @mbg.generated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.order_status
     *
     * @return the value of work_order.order_status
     *
     * @mbg.generated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.order_status
     *
     * @param orderStatus the value for work_order.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.question
     *
     * @return the value of work_order.question
     *
     * @mbg.generated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.question
     *
     * @param question the value for work_order.question
     *
     * @mbg.generated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.msg
     *
     * @return the value of work_order.msg
     *
     * @mbg.generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.msg
     *
     * @param msg the value for work_order.msg
     *
     * @mbg.generated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.annex
     *
     * @return the value of work_order.annex
     *
     * @mbg.generated
     */
    public String getAnnex() {
        return annex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.annex
     *
     * @param annex the value for work_order.annex
     *
     * @mbg.generated
     */
    public void setAnnex(String annex) {
        this.annex = annex == null ? null : annex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.gmt_create
     *
     * @return the value of work_order.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.gmt_create
     *
     * @param gmtCreate the value for work_order.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.gmt_modified
     *
     * @return the value of work_order.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.gmt_modified
     *
     * @param gmtModified the value for work_order.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}