package cn.yuntangnet.mapper;

import cn.yuntangnet.pojo.BusinessOrder;
import cn.yuntangnet.pojo.BusinessOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusinessOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_order
     *
     * @mbg.generated
     */
    long countByExample(BusinessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_order
     *
     * @mbg.generated
     */
    int deleteByExample(BusinessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_order
     *
     * @mbg.generated
     */
    int insert(BusinessOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_order
     *
     * @mbg.generated
     */
    int insertSelective(BusinessOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_order
     *
     * @mbg.generated
     */
    List<BusinessOrder> selectByExample(BusinessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_order
     *
     * @mbg.generated
     */
    BusinessOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BusinessOrder record, @Param("example") BusinessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BusinessOrder record, @Param("example") BusinessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusinessOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusinessOrder record);
}