package cn.yuntangnet.mapper;

import cn.yuntangnet.pojo.BusinessContent;
import cn.yuntangnet.pojo.BusinessContentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusinessContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    long countByExample(BusinessContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    int deleteByExample(BusinessContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    int insert(BusinessContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    int insertSelective(BusinessContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    List<BusinessContent> selectByExample(BusinessContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    BusinessContent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BusinessContent record, @Param("example") BusinessContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BusinessContent record, @Param("example") BusinessContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusinessContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusinessContent record);
}