package cn.yuntangnet.mapper;

import cn.yuntangnet.pojo.SystemContract;
import cn.yuntangnet.pojo.SystemContractExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SystemContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_contract
     *
     * @mbg.generated
     */
    long countByExample(SystemContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_contract
     *
     * @mbg.generated
     */
    int deleteByExample(SystemContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_contract
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_contract
     *
     * @mbg.generated
     */
    int insert(SystemContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_contract
     *
     * @mbg.generated
     */
    int insertSelective(SystemContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_contract
     *
     * @mbg.generated
     */
    List<SystemContract> selectByExample(SystemContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_contract
     *
     * @mbg.generated
     */
    SystemContract selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_contract
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SystemContract record, @Param("example") SystemContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_contract
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SystemContract record, @Param("example") SystemContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_contract
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_contract
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemContract record);
}