package cn.yuntangnet.mapper;

import cn.yuntangnet.pojo.UserWechat;
import cn.yuntangnet.pojo.UserWechatExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechat
     *
     * @mbg.generated
     */
    long countByExample(UserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechat
     *
     * @mbg.generated
     */
    int deleteByExample(UserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechat
     *
     * @mbg.generated
     */
    int insert(UserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechat
     *
     * @mbg.generated
     */
    int insertSelective(UserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechat
     *
     * @mbg.generated
     */
    List<UserWechat> selectByExample(UserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechat
     *
     * @mbg.generated
     */
    UserWechat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserWechat record, @Param("example") UserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserWechat record, @Param("example") UserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechat
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserWechat record);
}